#!/usr/bin/env sh

# source "$HOME/.config/yabai/colors.sh"

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

#read -r -d '' action <<- 'EOF'
#  recent_space_index="$(yabai -m query --spaces | 
#    jq -er 'map(select(.id | tostring == env.YABAI_RECENT_SPACE_ID))[0].index')"
#  if yabai -m query --windows --space "${recent_space_index}" |
#    jq -er 'length == 0'
#  then
#    yabai -m space "${recent_space_index}" --destroy
#  fi
#EOF
#
#yabai -m signal --add event='space_changed' action="${action}"
#
# global settings
yabai -m config                                 \
    external_bar                 all:30:0       \
    menubar_opacity              1.0            \
    mouse_follows_focus          off            \
    focus_follows_mouse          autoraise      \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_insertion_point       focused        \
    window_zoom_persist          on             \
    window_shadow                off            \
    window_animation_duration    0.001          \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               on             \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  12             \
    bottom_padding               14             \
    left_padding                 14             \
    right_padding                14             \
    window_gap                   18             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

yabai -m rule --add app="^(System Settings|System Information|Activity Monitor|FaceTime|Screen Sharing|Calculator|Stickies|TinkerTool|Progressive Downloader|Transmission|Airflow|OTP Manager|FortiClient)$" manage=off
yabai -m rule --add title="^(Tip of the Day|Settings)$" manage=off

yabai -m rule --add app="^Microsoft Teams$" space=1
yabai -m rule --add app="^Discord$" space=1
yabai -m rule --add app="^Telegram$" space=1
# yabai -m rule --add app="^IntelliJ IDEA$" space=5
yabai -m rule --add app="^IntelliJ IDEA$" title="^Update Project$" manage=off
yabai -m rule --add app="^DataGrip$" space=6
# yabai -m rule --add app="^KakaoTalk$" space=3

yabai -m signal --add event=window_created action="sketchybar -m --trigger window_change &> /dev/null"
yabai -m signal --add event=window_destroyed action="sketchybar -m --trigger window_change &> /dev/null"

#yabai -m signal --add event=application_activated action="yabai -m space --focus $(yabai -m query --windows --window | jq -r '.space')"

echo "yabai configuration loaded.."
