#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh" # Loads all defined icons

ITEM_DIR="$CONFIG_DIR/items" # Directory where the items are configured
PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored

FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDINGS=4

# # Setting up and starting the helper process
# HELPER=git.felix.helper
# killall helper
# (cd $CONFIG_DIR/helper && make)
# $CONFIG_DIR/helper/helper $HELPER > /dev/null 2>&1 &
#
# # Unload the macOS on screen indicator overlay for volume change
# launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

# Setting up the general bar appearance of the bar
bar=(
  color=$TRANSPARENT
  # color=$COLOR_BL2
  height=30
  y_offset=4
  padding_left=4
  padding_right=6
  corner_radius=18
  topmost=off
  margin=50
  position=top
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  padding_left=4 
  padding_right=4 
  
  background.border_color=$COLOR_WHITE_BRIGHT 
  # background.color=$BACKGROUND_1
  # background.border_color=$BACKGROUND_2
  background.border_width=2 
  background.height=26
  background.corner_radius=8
  
  icon.color=$COLOR_WHITE_BRIGHT 
  icon.highlight_color=$COLOR_BACKGROUND 
  icon.padding_left=6 
  icon.padding_right=2 
  icon.font="$FONT:Regular:14.0" 
  
  label.color=$COLOR_WHITE_BRIGHT 
  label.highlight_color=$COLOR_BACKGROUND 
  label.padding_left=2 
  label.padding_right=6 
  label.font="$FONT:Semibold:13.0"
)

sketchybar --default "${defaults[@]}"

menu_defaults=(
  popup.blur_radius=32
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.background.corner_radius=$PADDINGS
  popup.background.shadow.drawing=on
  popup.background.shadow.color=$(getcolor black 50)
  popup.background.shadow.angle=90
  popup.background.shadow.distance=16
)

menu_item_defaults=(
  label.font="$FONT:Regular:13"
  padding_left=$PADDINGS
  padding_right=$PADDINGS
  icon.padding_left=0
  icon.color=$HIGHLIGHT
  background.color=$TRANSPARENT
  scroll_texts=on
)


############################# Left ########################
# source "$ITEM_DIR/apple.sh"
# aerospace spaces.sh
# source "$ITEM_DIR/spaces.sh"

# yabai spaces.sh
source "$ITEM_DIR/yabai_spaces.sh"
source "$ITEM_DIR/front_app.sh"
source "$ITEM_DIR/yabai.sh"

############################# Center ########################
# source "$ITEM_DIR/spotify.sh"
# source "$ITEM_DIR/media.sh"

############################# Right ########################
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/keyboard.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/network.sh"
source "$ITEM_DIR/volume.sh"

source "$ITEM_DIR/weather.sh"

sketchybar --hotload on

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
